package com.demo.model;

public class Aluminum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.CSMMBR_NAME
     *
     * @mbggenerated
     */
    private String csmmbrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.FAMILY
     *
     * @mbggenerated
     */
    private String family;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.SPECIFICATION
     *
     * @mbggenerated
     */
    private String specification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.FORM
     *
     * @mbggenerated
     */
    private String form;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.TEMPER
     *
     * @mbggenerated
     */
    private String temper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.TEMPERATURE
     *
     * @mbggenerated
     */
    private String temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.DENSITY
     *
     * @mbggenerated
     */
    private String density;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.BOOKS
     *
     * @mbggenerated
     */
    private String books;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.AIRCRAFTID
     *
     * @mbggenerated
     */
    private String aircraftid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.TH_MIN
     *
     * @mbggenerated
     */
    private String thMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.TH_MAX
     *
     * @mbggenerated
     */
    private String thMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.BASIS
     *
     * @mbggenerated
     */
    private String basis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.DIRECTION
     *
     * @mbggenerated
     */
    private String direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.E
     *
     * @mbggenerated
     */
    private String e;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.E_C
     *
     * @mbggenerated
     */
    private String eC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.F_CY
     *
     * @mbggenerated
     */
    private String fCy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.F_SU
     *
     * @mbggenerated
     */
    private String fSu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.G
     *
     * @mbggenerated
     */
    private String g;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.NU
     *
     * @mbggenerated
     */
    private String nu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.ID
     *
     * @return the value of aluminum.ID
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.ID
     *
     * @param id the value for aluminum.ID
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.CSMMBR_NAME
     *
     * @return the value of aluminum.CSMMBR_NAME
     * @mbggenerated
     */
    public String getCsmmbrName() {
        return csmmbrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.CSMMBR_NAME
     *
     * @param csmmbrName the value for aluminum.CSMMBR_NAME
     * @mbggenerated
     */
    public void setCsmmbrName(String csmmbrName) {
        this.csmmbrName = csmmbrName == null ? null : csmmbrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.FAMILY
     *
     * @return the value of aluminum.FAMILY
     * @mbggenerated
     */
    public String getFamily() {
        return family;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.FAMILY
     *
     * @param family the value for aluminum.FAMILY
     * @mbggenerated
     */
    public void setFamily(String family) {
        this.family = family == null ? null : family.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.SPECIFICATION
     *
     * @return the value of aluminum.SPECIFICATION
     * @mbggenerated
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.SPECIFICATION
     *
     * @param specification the value for aluminum.SPECIFICATION
     * @mbggenerated
     */
    public void setSpecification(String specification) {
        this.specification = specification == null ? null : specification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.FORM
     *
     * @return the value of aluminum.FORM
     * @mbggenerated
     */
    public String getForm() {
        return form;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.FORM
     *
     * @param form the value for aluminum.FORM
     * @mbggenerated
     */
    public void setForm(String form) {
        this.form = form == null ? null : form.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.TEMPER
     *
     * @return the value of aluminum.TEMPER
     * @mbggenerated
     */
    public String getTemper() {
        return temper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.TEMPER
     *
     * @param temper the value for aluminum.TEMPER
     * @mbggenerated
     */
    public void setTemper(String temper) {
        this.temper = temper == null ? null : temper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.TEMPERATURE
     *
     * @return the value of aluminum.TEMPERATURE
     * @mbggenerated
     */
    public String getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.TEMPERATURE
     *
     * @param temperature the value for aluminum.TEMPERATURE
     * @mbggenerated
     */
    public void setTemperature(String temperature) {
        this.temperature = temperature == null ? null : temperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.DENSITY
     *
     * @return the value of aluminum.DENSITY
     * @mbggenerated
     */
    public String getDensity() {
        return density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.DENSITY
     *
     * @param density the value for aluminum.DENSITY
     * @mbggenerated
     */
    public void setDensity(String density) {
        this.density = density == null ? null : density.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.BOOKS
     *
     * @return the value of aluminum.BOOKS
     * @mbggenerated
     */
    public String getBooks() {
        return books;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.BOOKS
     *
     * @param books the value for aluminum.BOOKS
     * @mbggenerated
     */
    public void setBooks(String books) {
        this.books = books == null ? null : books.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.AIRCRAFTID
     *
     * @return the value of aluminum.AIRCRAFTID
     * @mbggenerated
     */
    public String getAircraftid() {
        return aircraftid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.AIRCRAFTID
     *
     * @param aircraftid the value for aluminum.AIRCRAFTID
     * @mbggenerated
     */
    public void setAircraftid(String aircraftid) {
        this.aircraftid = aircraftid == null ? null : aircraftid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.TH_MIN
     *
     * @return the value of aluminum.TH_MIN
     * @mbggenerated
     */
    public String getThMin() {
        return thMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.TH_MIN
     *
     * @param thMin the value for aluminum.TH_MIN
     * @mbggenerated
     */
    public void setThMin(String thMin) {
        this.thMin = thMin == null ? null : thMin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.TH_MAX
     *
     * @return the value of aluminum.TH_MAX
     * @mbggenerated
     */
    public String getThMax() {
        return thMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.TH_MAX
     *
     * @param thMax the value for aluminum.TH_MAX
     * @mbggenerated
     */
    public void setThMax(String thMax) {
        this.thMax = thMax == null ? null : thMax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.BASIS
     *
     * @return the value of aluminum.BASIS
     * @mbggenerated
     */
    public String getBasis() {
        return basis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.BASIS
     *
     * @param basis the value for aluminum.BASIS
     * @mbggenerated
     */
    public void setBasis(String basis) {
        this.basis = basis == null ? null : basis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.DIRECTION
     *
     * @return the value of aluminum.DIRECTION
     * @mbggenerated
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.DIRECTION
     *
     * @param direction the value for aluminum.DIRECTION
     * @mbggenerated
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.E
     *
     * @return the value of aluminum.E
     * @mbggenerated
     */
    public String getE() {
        return e;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.E
     *
     * @param e the value for aluminum.E
     * @mbggenerated
     */
    public void setE(String e) {
        this.e = e == null ? null : e.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.E_C
     *
     * @return the value of aluminum.E_C
     * @mbggenerated
     */
    public String geteC() {
        return eC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.E_C
     *
     * @param eC the value for aluminum.E_C
     * @mbggenerated
     */
    public void seteC(String eC) {
        this.eC = eC == null ? null : eC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.F_CY
     *
     * @return the value of aluminum.F_CY
     * @mbggenerated
     */
    public String getfCy() {
        return fCy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.F_CY
     *
     * @param fCy the value for aluminum.F_CY
     * @mbggenerated
     */
    public void setfCy(String fCy) {
        this.fCy = fCy == null ? null : fCy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.F_SU
     *
     * @return the value of aluminum.F_SU
     * @mbggenerated
     */
    public String getfSu() {
        return fSu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.F_SU
     *
     * @param fSu the value for aluminum.F_SU
     * @mbggenerated
     */
    public void setfSu(String fSu) {
        this.fSu = fSu == null ? null : fSu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.G
     *
     * @return the value of aluminum.G
     * @mbggenerated
     */
    public String getG() {
        return g;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.G
     *
     * @param g the value for aluminum.G
     * @mbggenerated
     */
    public void setG(String g) {
        this.g = g == null ? null : g.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aluminum.NU
     *
     * @return the value of aluminum.NU
     * @mbggenerated
     */
    public String getNu() {
        return nu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aluminum.NU
     *
     * @param nu the value for aluminum.NU
     * @mbggenerated
     */
    public void setNu(String nu) {
        this.nu = nu == null ? null : nu.trim();
    }
}