package com.demo.model;

import lombok.Data;

import java.io.Serializable;

/**
 * @author 苏若墨
 */
@Data
public class Aluminum implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.CSMMBR_NAME
     *
     * @mbggenerated
     */
    private String csmmbrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.FAMILY
     *
     * @mbggenerated
     */
    private String family;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.SPECIFICATION
     *
     * @mbggenerated
     */
    private String specification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.FORM
     *
     * @mbggenerated
     */
    private String form;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.TEMPER
     *
     * @mbggenerated
     */
    private String temper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.TEMPERATURE
     *
     * @mbggenerated
     */
    private String temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.DENSITY
     *
     * @mbggenerated
     */
    private String density;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.BOOKS
     *
     * @mbggenerated
     */
    private String books;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.AIRCRAFTID
     *
     * @mbggenerated
     */
    private String aircraftid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.TH_MIN
     *
     * @mbggenerated
     */
    private String thMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.TH_MAX
     *
     * @mbggenerated
     */
    private String thMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.BASIS
     *
     * @mbggenerated
     */
    private String basis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.DIRECTION
     *
     * @mbggenerated
     */
    private String direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.E
     *
     * @mbggenerated
     */
    private String e;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.E_C
     *
     * @mbggenerated
     */
    private String eC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.F_CY
     *
     * @mbggenerated
     */
    private String fCy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.F_SU
     *
     * @mbggenerated
     */
    private String fSu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.G
     *
     * @mbggenerated
     */
    private String g;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aluminum.NU
     *
     * @mbggenerated
     */
    private String nu;

}